version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - '${POSTGRES_EXTERNAL_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
volumes:
  db: